lawas_1 = input("Masukkan daftar belanja 1: ")
lawas_2 = input("Masukkan daftar belanja 2: ")
anyar_1 = input("Tambahkan data ke daftar belanja 1: ")
anyar_2 = input("Tambahkan data ke daftar belanja 2: ")
print("Daftar belanja 1 adalah " + lawas_1 + ", " + anyar_1)
print("Daftar belanja 2 adalah " + lawas_2 + ", " + anyar_2)